apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearchPublisher.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.elasticsearchPublisher.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.elasticsearchPublisher.component }}
    spec:
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.elasticsearchPublisher.name }}
          image: "{{ .Values.elasticsearchPublisher.image }}:{{ .Values.elasticsearchPublisher.tag }}"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime"]
