apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearchSuperdesk.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.elasticsearchSuperdesk.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.elasticsearchSuperdesk.component }}
    spec:
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.elasticsearchSuperdesk.component }}
          image: "{{ .Values.elasticsearchSuperdesk.image }}:{{ .Values.elasticsearchSuperdesk.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 9200
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
