apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2-$3/$5
#    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSCOOKIE"
#    nginx.ingress.kubernetes.io/session-cookie-path: /
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter 'http://localhost:5000/api/client_config' 'http://192.168.64.6/api';

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: superdesk-service-ip
              servicePort: 9000
          - path: /api
            backend:
              serviceName: superdesk-service-ip
              servicePort: 5000
          - path: /contentapi/
            backend:
              serviceName: superdesk-service-ip
              servicePort: 5400
          - path: /ws/
            backend:
              serviceName: superdesk-service-ip
              servicePort: 5100