apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: memcached
  template:
    metadata:
      labels:
        component: memcached
    spec:
      containers:
        - name: memcached
          image: memcached
          ports:
            - containerPort: 11211
