apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.memcached.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.memcached.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.memcached.component }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: instance/type
                    operator: NotIn
                    values:
                      - lb
      containers:
        - name: {{ .Values.memcached.name }}
          image: {{ .Values.memcached.image }}
          ports:
            - containerPort: 11211
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
