apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.mongodb.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.mongodb.component }}
    spec:
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: {{ .Values.mongodb.name }}
          image: "{{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
              subPath: mongodb

