apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.nginx.component }}
  ports:
    - name: http
      port: 80
      targetPort: 80
