apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.nginx.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.nginx.component }}
    spec:
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
      volumes:
        - name: publisher-storage
          persistentVolumeClaim:
            claimName: publisher-persistent-volume-claim
      imagePullSecrets:
      - name: harbor-access
      containers:
        - name: nginxpub
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 80
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/www/publisher/public/uploads
              name: publisher-storage
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime"]
