apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.nginx.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.nginx.component }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: instance/type
                    operator: NotIn
                    values:
                      - lb
      volumes:
        - name: publisher-storage
          persistentVolumeClaim:
            claimName: publisher-persistent-volume-claim
      containers:
        - name: nginxpub
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/publisher/public/uploads
              name: publisher-storage
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime"]
      imagePullSecrets:
        - name: harbor-access
