apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.postgres.component }}
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
