apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.publisher.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.publisher.component }}
  ports:
    - name: fe
      port: 9000
      targetPort: 9000
