apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      component: php
  template:
    metadata:
      labels:
        component: php
    spec:
      containers:
        - name: php
          image: mdridi/web-publisher
          resources:
            limits:
              memory: 6Gi
            requests:
              memory: 6Gi
          ports:
            - containerPort: 9000

#          command: ["/bin/sh"]
#          args: ["-c", "while true; do echo hello; sleep 10;done"]
