apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.publisher.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.publisher.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.publisher.component }}
    spec:
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
      volumes:
        - name: publisher-storage
          persistentVolumeClaim:
            claimName: publisher-persistent-volume-claim
      imagePullSecrets:
      - name: harbor-access
      containers:
        - name: php
          image: "{{ .Values.publisher.image }}:{{ .Values.publisher.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 128Gi
            requests:
              cpu: "8"
              memory: 128Gi
          ports:
            - containerPort: 9000
          volumeMounts:
        {{- if .Values.publisher.volumeMounts }}
{{- toYaml .Values.publisher.volumeMounts | nindent 12}}
        {{- end }}
          env:
            - name: APP_ENV
              value: {{ .Values.appEnv | quote }}
            - name: APP_DEBUG
              value: {{ .Values.appDebug | quote }}
            - name: CORS_ALLOW_ORIGIN
              value: "{{ .Values.proto }}://{{ .Values.publisher.superdeskHost }}"
            - name: SUPERDESK_SERVERS
              value: "[\"{{ .Values.proto }}://{{ .Values.publisher.superdeskHost }}\"]"
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: FIXTURES_TYPE
              value: {{ .Values.appEnv }} 
        {{- if .Values.publisher.env }}
          {{- toYaml .Values.publisher.env | nindent 12 }}
        {{end}}
