apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    component: rabbitmq
  ports:
    - name: rabbet
      port: 5672
      targetPort: 5672
    - name: rabbit
      port: 15672
      targetPort: 15672
