apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
