apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.supervisor.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.supervisor.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.supervisor.component }}
    spec:
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
      imagePullSecrets:
      - name: harbor-access
      containers:
        - name: supervisor
          image: "{{ .Values.supervisor.image }}:{{ .Values.supervisor.tag }}"
          ports:
        {{- if .Values.supervisor.ports }}
{{- toYaml .Values.supervisor.ports | nindent 12}}
        {{- end }}
          volumeMounts:
        {{- if .Values.supervisor.volumeMounts }}
{{- toYaml .Values.supervisor.volumeMounts | nindent 12}}
        {{- end }}
          env:
            - name: APP_DEBUG
              value: {{ .Values.appDebug | quote }}
            - name: APP_ENV
              value: {{ .Values.appEnv }}
            - name: CACHE_SERVERS
              value: '["{{ .Values.superdesk.swpHost }}"]'
            # for prod environments set the secret token (from SD > Settings > Subscribers):
            # php bin/console swp:organization:update OrganizationName --secretToken secret_token
            - name: CORS_ALLOW_ORIGIN
              value: '["{{ .Values.proto }}://{{ .Values.superdesk.swpHost }}", "{{ .Values.proto }}://{{ .Values.publisher.superdeskHost }}"]'
        {{- if .Values.supervisor.env }}
          {{- toYaml .Values.supervisor.env | nindent 12 }}
        {{- end}}
      volumes:
        - name: publisher-storage
          persistentVolumeClaim:
            claimName: publisher-persistent-volume-claim
