apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.superdesk.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.superdesk.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.superdesk.component }}
    spec:
      volumes:
        - name: superdesk-storage
          persistentVolumeClaim:
            claimName: superdesk-persistent-volume-claim
      containers:
        - name: client
          image: "{{ .Values.superdesk.image }}:{{ .Values.superdesk.tag }}"
          resources:
            limits:
              memory: 5Gi
            requests:
              memory: 5Gi
          ports:
            - containerPort: 9000
            - containerPort: 5000
            - containerPort: 5100
            - containerPort: 5400
            - containerPort: 443
            - containerPort: 80
          env:
            - name: HOST
              value: "{{ .Values.superdesk.baseUrl }}"
            - name: DB_HOST
              value: "mongodb"
            - name: DB_NAME
              value: "superdesk"
            - name: SUPERDESK_URL
              value: "{{ .Values.proto }}://{{ .Values.superdesk.baseUrl }}/api"
            - name: CONTENTAPI_URL
              value: "{{ .Values.proto }}://{{ .Values.superdesk.baseUrl }}/contentapi"
            - name: SUPERDESK_WS_URL
              value: "wss://{{ .Values.superdesk.baseUrl }}/ws"
            - name: SUPERDESK_CLIENT_URL
              value: "{{ .Values.proto}}://{{ .Values.superdesk.baseUrl }}"
            - name: DOCKER_IP
              value: "superdesk"
            - name: MONGO_URI
              value: "mongodb://mongodb/superdesk"
            - name: LEGAL_ARCHIVE_URI
              value: "mongodb://mongodb/superdesk_la"
            - name: ARCHIVED_URI
              value: "mongodb://mongodb/superdesk_ar"
            - name: ELASTICSEARCH_URL
              value: "http://elastic:9200"
            - name: ELASTICSEARCH_INDEX
              value: "superdesk"
            - name: CONTENTAPI_ELASTICSEARCH_INDEX
              value: "superdesk_ca"
            - name: CONTENTAPI_ELASTIC_INDEX
              value: "superdesk_ca"
            - name: CONTENTAPI_MONGO_URI
              value: "mongodb://mongodb/superdesk_ca"
            - name: REDIS_URL
              value: "redis://redis:6379/1"
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: SUPERDESK_CLIENT_CONFIG_FILE
              value: "superdesk-{{ .Values.stage }}.cloud.config.js"
          # probe after +5min (building client takes time) and check against :5000/api
          # TODO use values.yaml
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 360
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 320
            periodSeconds: 5
            successThreshold: 2
            timeoutSeconds: 2
      imagePullSecrets:
        - name: harbor-access
