apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.supervisor.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.supervisor.component }}
  {{- if .Values.supervisor.service.ports }}
  ports:
{{- toYaml .Values.supervisor.service.ports | nindent 4}}
  {{- end }}
