apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.superdesk.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.superdesk.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.superdesk.component }}
    spec:
      volumes:
        - name: superdesk-storage
          persistentVolumeClaim:
            claimName: superdesk-persistent-volume-claim
      containers:
        - name: client
          image: {{ .Values.superdesk.image }}
          resources:
            limits:
              memory: 5Gi
            requests:
              memory: 5Gi
          ports:
            - containerPort: 9000
            - containerPort: 5000
            - containerPort: 5100
            - containerPort: 5400

