apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.superdesk.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Values.superdesk.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.superdesk.component }}
    spec:
    {{- if .Values.affinity }}
      affinity:
    {{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
      volumes:
        - name: superdesk-storage
          persistentVolumeClaim:
            claimName: superdesk-persistent-volume-claim
      imagePullSecrets:
      - name: harbor-access
      containers:
        - name: client
          image: "{{ .Values.superdesk.image }}:{{ .Values.superdesk.tag }}"
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
<<<<<<< HEAD
              cpu: "8"
              memory: 128Gi
         {{- if .Values.superdesk.ports }}
=======
              cpu: "4"
              memory: 8Gi
>>>>>>> f7f29efc612331d6da8761441c7084beafe9157b
          ports:
{{- toYaml .Values.superdesk.ports | nindent 12}}
        {{- end }}
          env:
            - name: HOST
              value: "{{ .Values.superdesk.baseUrl }}"
            - name: SUPERDESK_URL
              value: "{{ .Values.proto }}://{{ .Values.superdesk.baseUrl }}/api"
            - name: CONTENTAPI_URL
              value: "{{ .Values.proto }}://{{ .Values.superdesk.baseUrl }}/contentapi"
            - name: SUPERDESK_WS_URL
              value: "wss://{{ .Values.superdesk.baseUrl }}/ws"
            - name: SUPERDESK_CLIENT_URL
              value: "{{ .Values.proto}}://{{ .Values.superdesk.baseUrl }}"
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: SUPERDESK_CLIENT_CONFIG_FILE
<<<<<<< HEAD
              value: "superdesk-{{ .Values.stage }}.cloud.config.js"          
        {{- if .Values.superdesk.env }}
          {{- toYaml .Values.superdesk.env | nindent 12 }}
        {{- end}}
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 360
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 320
            periodSeconds: 5
            successThreshold: 2
            timeoutSeconds: 2
=======
              value: "superdesk-{{ .Values.stage }}.cloud.config.js"
      imagePullSecrets:
        - name: harbor-access
>>>>>>> f7f29efc612331d6da8761441c7084beafe9157b
