# Superdesk configuration for Funkedigital

replicaCount: 1
proto: https
stage: stage
appEnv: prod
appDebug: 0
timezone: Europe/Berlin

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: instance/type
              operator: NotIn
              values:
                - lb

elasticsearchPublisher:
  name: elasticsearch
  component: elasticsearch
  image: elasticsearch
  tag: 5.6
  serviceName: elasticsearch

elasticsearchSuperdesk:
  name: elastic-deployment
  component: elastic
  image: elasticsearch
  tag: 2.4-alpine
  serviceName: elastic

# mongodb configuration
mongodb:
  name: mongodb

  # service port for mongodb
  port: 27017

  # repo for mongodb
  image:
    repository: mongo
    tag: 3.4
  serviceName: mongodb

  # pvc for mongodb
  persistence:
    enabled: true
    mountPath: /data/db
    accessModes:
      - ReadWriteMany
    size: 100Gi

nginx:
  name: nginx-deployment
  component: nginx
  image: harbor.cloud.funkedigital.de/superdesk/stage/nginx
  tag: latest
  serviceName: publisher

# Postgresql confgiuration
postgresql:

  # postgres password and database
  # change it if you are using different db and password in superdesk
  # postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlDatabase: "publications"

  # pvc for postgresql storage
  persistence:
    enabled: true
    size: 50Gi

publisher:
  name: php
  component: php
  image: harbor.cloud.funkedigital.de/superdesk/stage/php
  tag: latest
  serviceName: php
  superdeskHost: "superdesk-test.cloud.funkedigital.de"
  pvcSize: 1Ti

# configuration for rabbitmq
rabbitmq:
  replicas: 3

  securityContext:
    enabled: false

  # enable it if you want rbac for rabbitmq management
  name: rabbitmq

  # change it if other service type is prefer
  service:
    type: ClusterIP
    nodePort: 5672
    managerPort: 15672

  # env for timezone
  env:
    - name: TZ
      value: Europe/Berlin

# configuration for redis
redis:
  name: redis
  redisPort: 6379

  # image for redis  
  # image:
    # repository: bitnami/redis
    # tag: 5.0
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: instance/type
                  operator: NotIn
                  values:
                    - lb
  slave:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: instance/type
                  operator: NotIn
                  values:
                    - lb

# confiration fxor memcached
memcached:
  # replica size for memcached
  replicas: 3

  # service port for memached
  service:
    port: 11211

  # affinity for memcached
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                  - lb

superdesk:
  name: superdesk-deployment
  component: web
  image: harbor.cloud.funkedigital.de/superdesk/stage/superdesk
  tag: latest
  serviceName: superdesk-service-ip
  baseUrl: "superdesk-test.cloud.funkedigital.de"
  swpHost: "publisher-test.cloud.funkedigital.de"
  pvcSize: 1Ti

supervisor:
  name: supervisor-deployment
  component: supervisor
  image: harbor.cloud.funkedigital.de/superdesk/stage/supervisor
  tag: latest
  serviceName: supervisor

service:
  type: ClusterIP

resources:
  limits:
    cpu: 7
    memory: 13Gi
  requests:
    cpu: 7
    memory: 13Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.org/client-max-body-size: "1024m"
  hosts:
    - host: superdesk-test.cloud.funkedigital.de
      paths:
        - path: /
          backend:
            serviceName: superdesk-service-ip
            servicePort: 80
        - path: /api
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5000
        - path: /contentapi
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5400
        - path: /ws
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5100
    - host: publisher-test.cloud.funkedigital.de
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
        - path: /ws
          backend:
            serviceName: supervisor
            servicePort: 8080
    - host: waz-test.cloud.funkedigital.de
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
        - path: /ws
          backend:
            serviceName: supervisor
            servicePort: 8080
    - host: test.wmn.de
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
        - path: /ws
          backend:
            serviceName: supervisor
            servicePort: 8080
  tls:
    - hosts:
        - test.wmn.de
      secretName: test.wmn.de.tls
    - hosts:
        - superdesk-test.cloud.funkedigital.de
      secretName: superdesk-test.tls
    - hosts:
        - publisher-test.cloud.funkedigital.de
      secretName: publisher-test.tls
    - hosts:
        - waz-test.cloud.funkedigital.de
      secretName: waz-test.cloud.funkedigital.de.tls

