# Superdesk configuration for Funkedigital

replicaCount: 1
proto: https
stage: stage
appEnv: prod
appDebug: 0
timezone: Europe/Berlin

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: instance/type
              operator: NotIn
              values:
                - lb

elasticsearchPublisher:
  name: elasticsearch
  component: elasticsearch
  image: elasticsearch
  tag: 5.6
  serviceName: elasticsearch

elasticsearchSuperdesk:
  name: elastic-deployment
  component: elastic
  image: elasticsearch
  tag: 2.4-alpine
  serviceName: elastic

# mongodb configuration
mongodb:
  name: mongodb
  fullnameOverride: "mongodb"
  # service port for mongodb
  port: 27017

  # repo for mongodb
  image:
    repository: mongo
    tag: 3.4
  serviceName: mongodb

  # pvc for mongodb
  persistence:
    enabled: true
    mountPath: /data/db
    accessModes:
      - ReadWriteMany
    size: 100Gi

nginx:
  name: nginx-deployment
  component: nginx
  image: harbor.cloud.funkedigital.de/superdesk/stage/nginx
  tag: latest
  serviceName: publisher

# Postgresql confgiuration
postgresql:
  fullnameOverride: "postgres"
  # postgres password and database
  # change it if you are using different db and password in superdesk
  # postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlDatabase: "publications"

  # pvc for postgresql storage
  persistence:
    enabled: true
    size: 50Gi

publisher:
  name: php
  component: php
  image: harbor.cloud.funkedigital.de/superdesk/stage/php
  tag: latest
  serviceName: php
  superdeskHost: "superdesk-test.cloud.funkedigital.de"
  pvcSize: 1Ti

  volumeMounts:
    - mountPath: /var/www/publisher/public/bundles/_themes
      name: publisher-storage
    - mountPath: /var/www/publisher/public/uploads
      name: publisher-storage
    - mountPath: /var/www/publisher/templates
      name: publisher-storage
    - mountPath: /var/www/publisher/app/themes
      name: publisher-storage
    - mountPath: /var/www/publisher/app/meta
      name: publisher-storage
    - mountPath: /var/www/publisher/var/cache/dev
      name: publisher-storage
    - mountPath: /var/www/publisher/var/log
      name: publisher-storage
  env:
    - name: DATABASE_URL
      value: "pgsql://postgres:postgres@postgres/publications"

    - name: ELASTICA_HOST
      value: "elasticsearch"
    - name: ELASTICA_PORT
      value: "9200"
    - name: APP_SECRET
      valueFrom:
        secretKeyRef:
          name: publisher-app-secret
          key: APP_SECRET
    - name: DOCTRINE_CACHE_DRIVER
      value: "memcached"
    - name: SWP_DOMAIN
      value: "publisher"
    - name: SENTRY_DSN
      value: "false"
    - name: MAILER_URL
      value: "smtp://localhost"

    - name: ELASTICA_INDEX_NAME
      value: "swp_index-docker"
    - name: FS_MAIN_ADAPTER
      value: "local_adapter"
    - name: SESSION_MEMCACHED_HOST
      value: "memcached"

    - name: SESSION_MEMCACHED_PORT
      value: "11211"
    - name: SESSION_MEMCACHED_PREFIX
      value: "sess"
    - name: SESSION_MEMCACHED_EXPIRE
      value: "3600"
    - name: RABBIT_MQ_HOST
      value: "rabbitmq"
    - name: RABBIT_MQ_PORT
      value: "5672"
    - name: RABBIT_MQ_USER
      value: "guest"
    - name: RABBIT_MQ_PASSWORD
      value: "guest"
    - name: WEBSOCKET_PORT
      value: "443"
    - name: WEBSOCKET_HOST
      value: "127.0.0.1"


# configuration for rabbitmq
rabbitmq:
  replicas: 1

  securityContext:
    enabled: false

  # enable it if you want rbac for rabbitmq management
  name: rabbitmq

  # change it if other service type is prefer
  service:
    type: ClusterIP
    nodePort: 5672
    managerPort: 15672

  # env for timezone
  env:
    - name: TZ
      value: Europe/Berlin

# configuration for redis
redis:
  fullnameOverride: "redis"
  redisPort: 6379

  # image for redis  
  # image:
    # repository: bitnami/redis
    # tag: 5.0
  master:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: instance/type
                  operator: NotIn
                  values:
                    - lb
  slave:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: instance/type
                  operator: NotIn
                  values:
                    - lb

# confiration fxor memcached
memcached:
  fullnameOverride: "memcached"

  # replica size for memcached
  replicas: 3

  # service port for memached
  service:
    port: 11211

  # affinity for memcached
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: instance/type
                operator: NotIn
                values:
                  - lb

superdesk:
  name: superdesk-deployment
  component: web
  image: harbor.cloud.funkedigital.de/superdesk/stage/superdesk
  tag: latest
  serviceName: superdesk-service-ip
  baseUrl: "superdesk-test.cloud.funkedigital.de"
  swpHost: "publisher-test.cloud.funkedigital.de"
  pvcSize: 1Ti

  ports:
    - containerPort: 9000
      protocol: TCP
    - containerPort: 5000
      protocol: TCP
    - containerPort: 5100
      protocol: TCP
    - containerPort: 5400
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    - containerPort: 80
      protocol: TCP
  
  env:
    - name: DB_HOST
      value: "mongodb"
    - name: DB_NAME
      value: "superdesk"
    - name: DOCKER_IP
      value: "superdesk"
    - name: MONGO_URI
      value: "mongodb://mongodb/superdesk"
    - name: LEGAL_ARCHIVE_URI
      value: "mongodb://mongodb/superdesk_la"
    - name: ARCHIVED_URI
      value: "mongodb://mongodb/superdesk_ar"
    - name: ELASTICSEARCH_URL
      value: "http://elastic:9200"
    - name: ELASTICSEARCH_INDEX
      value: "superdesk"
    - name: CONTENTAPI_ELASTICSEARCH_INDEX
      value: "superdesk_ca"
    - name: CONTENTAPI_ELASTIC_INDEX
      value: "superdesk_ca"
    - name: CONTENTAPI_MONGO_URI
      value: "mongodb://mongodb/superdesk_ca"
    - name: REDIS_URL
      value: "redis://redis:6379/1"

  service:
    ports:
      - name: fe
        port: 9000
        targetPort: 9000
      - name: be
        port: 5000
        targetPort: 5000
      - name: content-api
        port: 5400
        targetPort: 5400
      - name: ws-ser
        port: 5100
        targetPort: 5100
      - name: ws-sersd
        port: 443
        targetPort: 443
      - name: ws-sers
        port: 80
        targetPort: 80

supervisor:
  name: supervisor-deployment
  component: supervisor
  image: harbor.cloud.funkedigital.de/superdesk/stage/supervisor
  tag: latest
  serviceName: supervisor
  ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 5555
      protocol: TCP
  service:
    ports:
      - name: sup
        port: 5555
        targetPort: 5555
      - name: yup
        port: 8080
        targetPort: 8080
  env:
    - name: DATABASE_URL
      value: pgsql://postgres:postgres@postgres/publications
    - name: ELASTICA_HOST
      value: elasticsearch
    - name: ELASTICA_INDEX_NAME
      value: swp_index
    - name: ELASTICA_PORT
      value: "9200"
    - name: FS_MAIN_ADAPTER
      value: local_adapter
    - name: MESSENGER_TRANSPORT_DSN
      value: amqp://guest:guest@rabbitmq:5672/%2f/messages
    - name: RABBIT_MQ_HOST
      value: rabbitmq
    - name: RABBIT_MQ_PASSWORD
      value: guest
    - name: RABBIT_MQ_PORT
      value: "5672"
    - name: RABBIT_MQ_USER
      value: guest
    - name: RABBIT_MQ_VHOST
      value: /
    - name: TZ
      value: Europe/Berlin
    - name: WEBSOCKET_HOST
      value: 0.0.0.0
    - name: WEBSOCKET_PORT
      value: "8080"
  volumeMounts:
    - mountPath: /var/www/publisher/app/logs
      name: publisher-storage
    - mountPath: /var/www/publisher/public/uploads
      name: publisher-storage


service:
  type: ClusterIP

resources:
  limits:
    cpu: 7
    memory: 13Gi
  requests:
    cpu: 7
    memory: 13Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.org/client-max-body-size: "1024m"
  hosts:
    - host: superdesk-test.cloud.funkedigital.de
      paths:
        - path: /
          backend:
            serviceName: superdesk-service-ip
            servicePort: 80
        - path: /api
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5000
        - path: /contentapi
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5400
        - path: /ws
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5100
    - host: publisher-test.cloud.funkedigital.de
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
        - path: /ws
          backend:
            serviceName: supervisor
            servicePort: 8080
    - host: waz-test.cloud.funkedigital.de
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
        - path: /ws
          backend:
            serviceName: supervisor
            servicePort: 8080
    - host: test.wmn.de
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
        - path: /ws
          backend:
            serviceName: supervisor
            servicePort: 8080
  tls:
    - hosts:
        - test.wmn.de
      secretName: test.wmn.de.tls
    - hosts:
        - superdesk-test.cloud.funkedigital.de
      secretName: superdesk-test.tls
    - hosts:
        - publisher-test.cloud.funkedigital.de
      secretName: publisher-test.tls
    - hosts:
        - waz-test.cloud.funkedigital.de
      secretName: waz-test.cloud.funkedigital.de.tls

