replicaCount: 1

elasticsearchPublisher:
  name: elasticsearch
  component: elasticsearch
  image: elasticsearch
  tag: 5.6
  serviceName: elasticsearch

elasticsearchSuperdesk:
  name: elastic-deployment
  component: elastic
  image: elasticsearch
  tag: 2
  serviceName: elastic

memcached:
  name: memcached-deployment
  component: memcached
  image: memcached
  tag: latest
  serviceName: elastic

mongodb:
  name: mongodb-deployment
  component: mongodb
  image: mongo
  tag: 3.4
  serviceName: mongodb

nginx:
  name: nginx-deployment
  component: nginx
  image: mdridi/nginx-publisher
  tag: latest
  serviceName: publisher

postgres:
  name: postgres
  component: postgres
  image: postgres
  tag: latest
  serviceName: postgres

publisher:
  name: php
  component: php
  image: mdridi/web-publisher
  tag: latest
  serviceName: php

rabbitmq:
  name: rabbitmq-deployment
  component: rabbitmq
  image: rabbitmq
  tag: management
  serviceName: rabbitmq

redis:
  name: redis-deployment
  component: redis
  image: redis
  tag: 5.0
  serviceName: redis

superdesk:
  name: superdesk-deployment
  component: web
  image: mdridi/superdesk
  tag: latest
  serviceName: superdesk-service-ip

supervisor:
  name: supervisor-deployment
  component: supervisor
  image: mdridi/supervisor
  tag: latest
  serviceName: supervisor

service:
  type: ClusterIP

resources:
  limits:
    cpu: 7
    memory: 13Gi
  requests:
    cpu: 7
    memory: 13Gi

ingress:
  enabled: true
  hosts:
    - host: hasura.cloud.funkedigital.de
      paths: ['/']



