replicaCount: 1

elasticsearchPublisher:
  name: elasticsearch
  component: elasticsearch
  image: elasticsearch
  tag: 5.6
  serviceName: elasticsearch

elasticsearchSuperdesk:
  name: elastic-deployment
  component: elastic
  image: elasticsearch
  tag: 2
  serviceName: elastic

memcached:
  name: memcached-deployment
  component: memcached
  image: memcached
  tag: latest
  serviceName: memcached

mongodb:
  name: mongodb-deployment
  component: mongodb
  image: mongo
  tag: 3.4
  serviceName: mongodb

nginx:
  name: nginx-deployment
  component: nginx
  image: mdridi/nginx-publisher
  tag: latest
  serviceName: publisher

postgres:
  name: postgres
  component: postgres
  image: postgres
  tag: latest
  serviceName: postgres

publisher:
  name: php
  component: php
#  image: mdridi/publisher-dev
  image: mdridi/web-publisher
  tag: latest
  serviceName: php
  superdeskHost: 192.168.64.6

rabbitmq:
  name: rabbitmq-deployment
  component: rabbitmq
  image: rabbitmq
  tag: management
  serviceName: rabbitmq

redis:
  name: redis-deployment
  component: redis
  image: redis
  tag: 5.0
  serviceName: redis

superdesk:
  name: superdesk-deployment
  component: web
  image: mdridi/superdesk-prod
  tag: latest
  serviceName: superdesk-service-ip

supervisor:
  name: supervisor-deployment
  component: supervisor
  image: mdridi/supervisor
  tag: latest
  serviceName: supervisor

service:
  type: ClusterIP

resources:
  limits:
    cpu: 7
    memory: 13Gi
  requests:
    cpu: 7
    memory: 13Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: stage.wmn.de
      paths:
        - path: /
          backend:
            serviceName: stage-wmn-de
            servicePort: 80
    - host: superdesk
      paths:
        - path: /
          backend:
            serviceName: superdesk-service-ip
            servicePort: 80
        - path: /api
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5000
        - path: /contentapi
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5400
        - path: /ws
          backend:
            serviceName: superdesk-service-ip
            servicePort: 5100
    - host: publisher
      paths:
        - path: /
          backend:
            serviceName: publisher
            servicePort: 80
  tls:
    - hosts:
        - stage.wmn.de
      secretName: stage.wmn.de.tls
    - hosts:
        - superdesk
      secretName: superdesk.tls
    - hosts:
        - publisher
      secretName: publisher.tls

